export const RECEIVE_INIT = 'RECEIVE_INIT'
export const RECEIVE_SHOW_TRANSPORT_STATUS = 'RECEIVE_SHOW_TRANSPORT_STATUS'
export const RECEIVE_PLAY_MEDIA = 'RECEIVE_PLAY_MEDIA'
export const RECEIVE_STOP_MEDIA = 'RECEIVE_STOP_MEDIA'
export const RECEIVE_RELOAD = 'RECEIVE_RELOAD'

export const RELOAD = 'RELOAD'
export const TRANSITION_TO = 'TRANSITION_TO'

export const RECEIVE_UNAUTHORISED = 'RECEIVE_UNAUTHORISED'

export const HEY_MARVIN = 'HEY_MARVIN'
export const HEY_MARVIN_TIMEOUT = 'HEY_MARVIN_TIMEOUT'

export const MARVIN_TIMEOUT_INTERVAL = 8000

export const SEND_QUESTION = 'SEND_QUESTION'
export const RECEIVE_QUESTION_RESPONSE = 'RECEIVE_QUESTION_RESPONSE'

export const START_SPEAKING = 'START_SPEAKING'
export const STOP_SPEAKING = 'STOP_SPEAKING'

export const SPEECH_SYNTHESIS_VOICE = 'Google UK English Male'

export const INTENT_TRANSPORT_DISRUPTION = 'transport_disruption'

export const PROCESS_QUESTION_RESPONSE_STARTED = 'PROCESS_QUESTION_RESPONSE_STARTED'
export const PROCESS_QUESTION_RESPONSE_FINISHED = 'PROCESS_QUESTION_RESPONSE_FINISHED'
