port: 4321
updateInterval: 30000

localhost:
  - '127.0.0.1'
  - '0:0:0:0:0:0:0:1'
  - '::1'

auth:
  key: foo

calendars:
  - { id: oliver.woodings@gmail.com, name: oli }
  - { id: k9ajcj33fitet98ifjm6n56hgk@group.calendar.google.com, name: music }
  - { id: oliver.woodings@qubit.com, name: qubit }

apis:
  weather:
    key: apikey
    cityId: 2643743
  tfl:
    buses:
      - 93
      - 57
      - 131
      - 219
  huxley:
    key: apikey
    routes:
      - { from: wim, to: wat }
      - { from: wat, to: wim }
      - { from: wim, to: kng }
      - { from: kng, to: wim }
  wit:
    key: apikey
