port: 4321
updateInterval: 30000

localhost:
  - '127.0.0.1'
  - '0:0:0:0:0:0:0:1'
  - '::1'

auth:
  key: foo

apis:
  weather:
    key: apikey
    cityId: 2643743
  tfl:
    buses:
      - 93
      - 57
      - 131
      - 219
  huxley:
    key: apikey
    routes:
      - { from: wim, to: nem }
      - { from: nem, to: wim }
  wit:
    key: apikey
